version: "3.8"
services:
  client:
    image: anchor-bot-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  server:
    image: anchor-bot-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
